[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kpk-police-act-chatbot"
version = "0.1.0"
dependencies = [
    "streamlit",
    "other_dependencies",
]
